version: '2'

services:
  web:
    build: web
    volumes:
      - ./conf/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - api
    networks:
      - gnucash

  api:
    build: api
    links:
      - mysql
    networks:
      - gnucash

  mysql:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=gnucash
      - MYSQL_USER=gnucash
      - MYSQL_PASSWORD=--changeit--
    networks:
      - gnucash

  gnucash:
    image: potz/gnucash
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    links:
      - mysql
    networks:
      - gnucash

networks:
  gnucash:
    driver: bridge
